# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  selector:
    app: simple-app
  ports:
    - protocol: TCP 
      port: 8080 
      targetPort: 4001 
  type: NodePort